//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> lesson_id { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
